export const datas = [
  {
    id: 1,
    name: "ฉลาม",
    shop: "ร้านระฆัง",
    price: 85,
    quantity: 10,
    ppq: 8.5,
  },
  {
    id: 2,
    name: "M-150",
    shop: "ร้านระฆัง",
    price: 105,
    quantity: 10,
    ppq: 10.5,
  },
  {
    id: 3,
    name: "ปลากระป๋องมงกุฎทะเล",
    shop: "ร้านระฆัง",
    price: 115,
    quantity: 10,
    ppq: 11.5,
  },
  {
    id: 4,
    name: "ปลากระป๋องมงกุฎทะเล",
    shop: "ร้านบ้านชายนา",
    price: 118,
    quantity: 11,
    ppq: 10.72,
  },
  {
    id: 5,
    name: "รสดี 5 บ.",
    shop: "ร้านระฆัง",
    price: 55,
    quantity: 12,
    ppq: 4.58,
  },
  {
    id: 6,
    name: "ท่อยางยาว",
    shop: "ร้านระฆัง",
    price: 240,
    quantity: 25,
    ppq: 9.6,
  },
  {
    id: 7,
    name: "น้ำอัดลม 455",
    shop: "ร้านระฆัง",
    price: 160,
    quantity: 12,
    ppq: 13.33,
  },
  {
    id: 8,
    name: "ซันไลต์ขวด",
    shop: "ร้านระฆัง",
    price: 70,
    quantity: 6,
    ppq: 11.67,
  },
  {
    id: 9,
    name: "ซันไลต์ถุง",
    shop: "ร้านระฆัง",
    price: 50,
    quantity: 3,
    ppq: 16.67,
  },
  {
    id: 10,
    name: "สปอนเซอร์",
    shop: "ร้านระฆัง",
    price: 240,
    quantity: 24,
    ppq: 10,
  },
  {
    id: 11,
    name: "สปอนเซอร์",
    shop: "เซล",
    price: 250,
    quantity: 24,
    ppq: 10.42,
  },
  {
    id: 12,
    name: "ใบจาก",
    shop: "เซล",
    price: 43,
    quantity: 10,
    ppq: 4.3,
  },
  {
    id: 13,
    name: "ยาเส้นชาวนา",
    shop: "เซล",
    price: 40,
    quantity: 10,
    ppq: 4,
  },
  {
    id: 14,
    name: "ยาเส้นเซียน",
    shop: "เซล",
    price: 85,
    quantity: 20,
    ppq: 4.25,
  },
];
